import { Loan } from './Loan';
import { LoanPage } from './LoanPage';

export const LOAN_DATA: LoanPage = {
  content: [
    {
      id: 1,
      game: {
        id: 1,
        title: 'Azul',
        age: 6,
        category: { id: 1, name: 'Platformer' },
        author: { id: 1, name: 'Nintendo', nationality: 'Nationality 1' },
      },
      customer: { id: 1, name: 'John Doe' },
      loanDate: new Date('2020-01-01'),
      returnDate: new Date('2020-01-15'),
    },
    {
      id: 2,
      game: {
        id: 3,
        title: 'On Mars',
        age: 10,
        category: { id: 1, name: 'Platformer' },
        author: { id: 1, name: 'Nintendo', nationality: 'Nationality 1' },
      },
      customer: { id: 2, name: 'Jane Doe' },
      loanDate: new Date('2020-01-05'),
      returnDate: new Date('2020-01-15'),
    },
    {
      id: 3,
      game: {
        id: 4,
        title: 'Tetris',
        age: 10,
        category: { id: 2, name: 'Puzzle' },
        author: { id: 1, name: 'Author', nationality: 'Nationality 2' },
      },
      customer: { id: 1, name: 'John Doe' },
      loanDate: new Date('2020-01-05'),
      returnDate: new Date('2020-01-25'),
    },
    {
      id: 4,
      game: {
        id: 1,
        title: 'Azul',
        age: 6,
        category: { id: 1, name: 'Platformer' },
        author: { id: 1, name: 'Nintendo', nationality: 'Nationality 1' },
      },
      customer: { id: 1, name: 'John Doe' },
      loanDate: new Date('2020-01-01'),
      returnDate: new Date('2020-01-15'),
    },
    {
      id: 5,
      game: {
        id: 3,
        title: 'On Mars',
        age: 10,
        category: { id: 1, name: 'Platformer' },
        author: { id: 1, name: 'Nintendo', nationality: 'Nationality 1' },
      },
      customer: { id: 2, name: 'Jane Doe' },
      loanDate: new Date('2020-01-05'),
      returnDate: new Date('2020-01-15'),
    },
    {
      id: 6,
      game: {
        id: 4,
        title: 'Tetris',
        age: 10,
        category: { id: 2, name: 'Puzzle' },
        author: { id: 1, name: 'Author', nationality: 'Nationality 2' },
      },
      customer: { id: 1, name: 'John Doe' },
      loanDate: new Date('2020-01-05'),
      returnDate: new Date('2020-01-25'),
    },
    {
      id: 7,
      game: {
        id: 1,
        title: 'Azul',
        age: 6,
        category: { id: 1, name: 'Platformer' },
        author: { id: 1, name: 'Nintendo', nationality: 'Nationality 1' },
      },
      customer: { id: 1, name: 'John Doe' },
      loanDate: new Date('2020-01-01'),
      returnDate: new Date('2020-01-15'),
    },
    {
      id: 8,
      game: {
        id: 3,
        title: 'On Mars',
        age: 10,
        category: { id: 1, name: 'Platformer' },
        author: { id: 1, name: 'Nintendo', nationality: 'Nationality 1' },
      },
      customer: { id: 2, name: 'Jane Doe' },
      loanDate: new Date('2020-01-05'),
      returnDate: new Date('2020-01-15'),
    },
    {
      id: 9,
      game: {
        id: 4,
        title: 'Tetris',
        age: 10,
        category: { id: 2, name: 'Puzzle' },
        author: { id: 1, name: 'Author', nationality: 'Nationality 2' },
      },
      customer: { id: 1, name: 'John Doe' },
      loanDate: new Date('2020-01-05'),
      returnDate: new Date('2020-01-25'),
    },
    {
      id: 10,
      game: {
        id: 1,
        title: 'Azul',
        age: 6,
        category: { id: 1, name: 'Platformer' },
        author: { id: 1, name: 'Nintendo', nationality: 'Nationality 1' },
      },
      customer: { id: 1, name: 'John Doe' },
      loanDate: new Date('2020-01-01'),
      returnDate: new Date('2020-01-15'),
    },
    {
      id: 11,
      game: {
        id: 3,
        title: 'On Mars',
        age: 10,
        category: { id: 1, name: 'Platformer' },
        author: { id: 1, name: 'Nintendo', nationality: 'Nationality 1' },
      },
      customer: { id: 2, name: 'Jane Doe' },
      loanDate: new Date('2020-01-05'),
      returnDate: new Date('2020-01-15'),
    },
    {
      id: 12,
      game: {
        id: 4,
        title: 'Tetris',
        age: 10,
        category: { id: 2, name: 'Puzzle' },
        author: { id: 1, name: 'Author', nationality: 'Nationality 2' },
      },
      customer: { id: 1, name: 'John Doe' },
      loanDate: new Date('2020-01-05'),
      returnDate: new Date('2020-01-25'),
    },
  ],
  pageable: {
    pageSize: 5,
    pageNumber: 0,
    sort: [{ property: 'id', direction: 'ASC' }],
  },
  totalElements: 12,
};
